#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "../include/encode.h"

FILE *f_a1;
FILE *f_a1p;
FILE *f_a1r;
FILE *f_a1t;
FILE *f_a2;
FILE *f_a2p;
FILE *f_a2r;
FILE *f_a2t;
FILE *f_aLaw;
FILE *f_al;
FILE *f_ap;
FILE *f_app;
FILE *f_apr;
FILE *f_ax;
FILE *f_b1;
FILE *f_b1p;
FILE *f_b1r;
FILE *f_b2;
FILE *f_b2p;
FILE *f_b2r;
FILE *f_b3;
FILE *f_b3p;
FILE *f_b3r;
FILE *f_b4;
FILE *f_b4p;
FILE *f_b4r;
FILE *f_b5;
FILE *f_b5p;
FILE *f_b5r;
FILE *f_b6;
FILE *f_b6p;
FILE *f_b6r;
FILE *f_dlnx;
FILE *f_dlx;
FILE *f_dml;
FILE *f_dmlp;
FILE *f_dms;
FILE *f_dmsp;
FILE *f_dq;
FILE *f_dq0;
FILE *f_dq1;
FILE *f_dq2;
FILE *f_dq3;
FILE *f_dq4;
FILE *f_dq5;
FILE *f_dq6;
FILE *f_dql;
FILE *f_dqln;
FILE *f_dqs;
FILE *f_dsx;
FILE *f_dx;
FILE *f_fi;
FILE *f_I;
FILE *f_pcm;
FILE *f_pk0;
FILE *f_pk1;
FILE *f_pk2;
FILE *f_sd;
FILE *f_se;
FILE *f_sez;
FILE *f_sg;
FILE *f_sigpk;
FILE *f_slx;
FILE *f_sp;
FILE *f_sr;
FILE *f_sr0;
FILE *f_sr1;
FILE *f_sr2;
FILE *f_td;
FILE *f_tdp;
FILE *f_tdr;
FILE *f_tr;
FILE *f_u1;
FILE *f_u2;
FILE *f_u3;
FILE *f_u4;
FILE *f_u5;
FILE *f_u6;
FILE *f_wa1;
FILE *f_wa2;
FILE *f_wb1;
FILE *f_wb2;
FILE *f_wb3;
FILE *f_wb4;
FILE *f_wb5;
FILE *f_wb6;
FILE *f_wi;
FILE *f_y;
FILE *f_yl;
FILE *f_ylp;
FILE *f_yu;
FILE *f_yup;
FILE *f_yut;
FILE *f_input;
FILE *f_output;

int ONLY_TOP_LEVEL = 0;
void setOnlyTopLevel()
{
	ONLY_TOP_LEVEL = 1;
}

void openFiles()
{
	const char* userName = getenv("USER");
	char outPath[64];
	char fileDir[64];
	snprintf(outPath, sizeof(outPath), "/tmp/%s_sr_vec_out/", userName);
	char* mode = "w";

	mkdir(outPath, (S_IRWXU | S_IRWXG | S_IRWXO));
if (!ONLY_TOP_LEVEL) {
	snprintf(fileDir, sizeof(fileDir), "%sa1.t", outPath);
	f_a1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa1p.t", outPath);
	f_a1p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa1r.t", outPath);
	f_a1r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa1t.t", outPath);
	f_a1t = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa2.t", outPath);
	f_a2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa2p.t", outPath);
	f_a2p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa2r.t", outPath);
	f_a2r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sa2t.t", outPath);
	f_a2t = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%saLaw.t", outPath);
	f_aLaw = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sal.t", outPath);
	f_al = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sap.t", outPath);
	f_ap = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sapp.t", outPath);
	f_app = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sapr.t", outPath);
	f_apr = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sax.t", outPath);
	f_ax = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb1.t", outPath);
	f_b1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb1p.t", outPath);
	f_b1p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb1r.t", outPath);
	f_b1r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb2.t", outPath);
	f_b2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb2p.t", outPath);
	f_b2p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb2r.t", outPath);
	f_b2r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb3.t", outPath);
	f_b3 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb3p.t", outPath);
	f_b3p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb3r.t", outPath);
	f_b3r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb4.t", outPath);
	f_b4 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb4p.t", outPath);
	f_b4p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb4r.t", outPath);
	f_b4r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb5.t", outPath);
	f_b5 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb5p.t", outPath);
	f_b5p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb5r.t", outPath);
	f_b5r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb6.t", outPath);
	f_b6 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb6p.t", outPath);
	f_b6p = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sb6r.t", outPath);
	f_b6r = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdlnx.t", outPath);
	f_dlnx = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdlx.t", outPath);
	f_dlx = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdml.t", outPath);
	f_dml = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdmlp.t", outPath);
	f_dmlp = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdms.t", outPath);
	f_dms = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdmsp.t", outPath);
	f_dmsp = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq.t", outPath);
	f_dq = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq0.t", outPath);
	f_dq0 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq1.t", outPath);
	f_dq1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq2.t", outPath);
	f_dq2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq3.t", outPath);
	f_dq3 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq4.t", outPath);
	f_dq4 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq5.t", outPath);
	f_dq5 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdq6.t", outPath);
	f_dq6 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdql.t", outPath);
	f_dql = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdqln.t", outPath);
	f_dqln = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdqs.t", outPath);
	f_dqs = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdsx.t", outPath);
	f_dsx = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sdx.t", outPath);
	f_dx = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sfi.t", outPath);
	f_fi = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sI.t", outPath);
	f_I = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%spcm.t", outPath);
	f_pcm = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%spk0.t", outPath);
	f_pk0 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%spk1.t", outPath);
	f_pk1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%spk2.t", outPath);
	f_pk2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssd.t", outPath);
	f_sd = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sse.t", outPath);
	f_se = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssez.t", outPath);
	f_sez = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssg.t", outPath);
	f_sg = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssigpk.t", outPath);
	f_sigpk = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sslx.t", outPath);
	f_slx = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssp.t", outPath);
	f_sp = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssr.t", outPath);
	f_sr = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssr0.t", outPath);
	f_sr0 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssr1.t", outPath);
	f_sr1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%ssr2.t", outPath);
	f_sr2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%std.t", outPath);
	f_td = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%stdp.t", outPath);
	f_tdp = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%stdr.t", outPath);
	f_tdr = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%str.t", outPath);
	f_tr = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su1.t", outPath);
	f_u1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su2.t", outPath);
	f_u2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su3.t", outPath);
	f_u3 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su4.t", outPath);
	f_u4 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su5.t", outPath);
	f_u5 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%su6.t", outPath);
	f_u6 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swa1.t", outPath);
	f_wa1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swa2.t", outPath);
	f_wa2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb1.t", outPath);
	f_wb1 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb2.t", outPath);
	f_wb2 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb3.t", outPath);
	f_wb3 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb4.t", outPath);
	f_wb4 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb5.t", outPath);
	f_wb5 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swb6.t", outPath);
	f_wb6 = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%swi.t", outPath);
	f_wi = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sy.t", outPath);
	f_y = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%syl.t", outPath);
	f_yl = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%sylp.t", outPath);
	f_ylp = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%syu.t", outPath);
	f_yu = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%syup.t", outPath);
	f_yup = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%syut.t", outPath);
	f_yut = fopen(fileDir, mode);
}
	snprintf(fileDir, sizeof(fileDir), "%sinput.t", outPath);
	f_input = fopen(fileDir, mode);
	snprintf(fileDir, sizeof(fileDir), "%soutput.t", outPath);
	f_output = fopen(fileDir, mode);
}

int clockCount = 0;

void printVars(struct channel* c)
{
	fprintf(f_a1, "@%04X\t%06X\n", clockCount, c->a1);
	fprintf(f_a1p, "@%04X\t%06X\n", clockCount, c->a1p);
	fprintf(f_a1r, "@%04X\t%06X\n", clockCount, c->a1r);
	fprintf(f_a1t, "@%04X\t%06X\n", clockCount, c->a1t);
	fprintf(f_a2, "@%04X\t%06X\n", clockCount, c->a2);
	fprintf(f_a2p, "@%04X\t%06X\n", clockCount, c->a2p);
	fprintf(f_a2r, "@%04X\t%06X\n", clockCount, c->a2r);
	fprintf(f_a2t, "@%04X\t%06X\n", clockCount, c->a2t);
	fprintf(f_aLaw, "@%04X\t%06X\n", clockCount, c->aLaw);
	fprintf(f_al, "@%04X\t%06X\n", clockCount, c->al);
	fprintf(f_ap, "@%04X\t%06X\n", clockCount, c->ap);
	fprintf(f_app, "@%04X\t%06X\n", clockCount, c->app);
	fprintf(f_apr, "@%04X\t%06X\n", clockCount, c->apr);
	fprintf(f_ax, "@%04X\t%06X\n", clockCount, c->ax);
	fprintf(f_b1, "@%04X\t%06X\n", clockCount, c->b1);
	fprintf(f_b1p, "@%04X\t%06X\n", clockCount, c->b1p);
	fprintf(f_b1r, "@%04X\t%06X\n", clockCount, c->b1r);
	fprintf(f_b2, "@%04X\t%06X\n", clockCount, c->b2);
	fprintf(f_b2p, "@%04X\t%06X\n", clockCount, c->b2p);
	fprintf(f_b2r, "@%04X\t%06X\n", clockCount, c->b2r);
	fprintf(f_b3, "@%04X\t%06X\n", clockCount, c->b3);
	fprintf(f_b3p, "@%04X\t%06X\n", clockCount, c->b3p);
	fprintf(f_b3r, "@%04X\t%06X\n", clockCount, c->b3r);
	fprintf(f_b4, "@%04X\t%06X\n", clockCount, c->b4);
	fprintf(f_b4p, "@%04X\t%06X\n", clockCount, c->b4p);
	fprintf(f_b4r, "@%04X\t%06X\n", clockCount, c->b4r);
	fprintf(f_b5, "@%04X\t%06X\n", clockCount, c->b5);
	fprintf(f_b5p, "@%04X\t%06X\n", clockCount, c->b5p);
	fprintf(f_b5r, "@%04X\t%06X\n", clockCount, c->b5r);
	fprintf(f_b6, "@%04X\t%06X\n", clockCount, c->b6);
	fprintf(f_b6p, "@%04X\t%06X\n", clockCount, c->b6p);
	fprintf(f_b6r, "@%04X\t%06X\n", clockCount, c->b6r);
	fprintf(f_dlnx, "@%04X\t%06X\n", clockCount, c->dlnx);
	fprintf(f_dlx, "@%04X\t%06X\n", clockCount, c->dlx);
	fprintf(f_dml, "@%04X\t%06X\n", clockCount, c->dml);
	fprintf(f_dmlp, "@%04X\t%06X\n", clockCount, c->dmlp);
	fprintf(f_dms, "@%04X\t%06X\n", clockCount, c->dms);
	fprintf(f_dmsp, "@%04X\t%06X\n", clockCount, c->dmsp);
	fprintf(f_dq, "@%04X\t%06X\n", clockCount, c->dq);
	fprintf(f_dq0, "@%04X\t%06X\n", clockCount, c->dq0);
	fprintf(f_dq1, "@%04X\t%06X\n", clockCount, c->dq1);
	fprintf(f_dq2, "@%04X\t%06X\n", clockCount, c->dq2);
	fprintf(f_dq3, "@%04X\t%06X\n", clockCount, c->dq3);
	fprintf(f_dq4, "@%04X\t%06X\n", clockCount, c->dq4);
	fprintf(f_dq5, "@%04X\t%06X\n", clockCount, c->dq5);
	fprintf(f_dq6, "@%04X\t%06X\n", clockCount, c->dq6);
	fprintf(f_dql, "@%04X\t%06X\n", clockCount, c->dql);
	fprintf(f_dqln, "@%04X\t%06X\n", clockCount, c->dqln);
	fprintf(f_dqs, "@%04X\t%06X\n", clockCount, c->dqs);
	fprintf(f_dsx, "@%04X\t%06X\n", clockCount, c->dsx);
	fprintf(f_dx, "@%04X\t%06X\n", clockCount, c->dx);
	fprintf(f_fi, "@%04X\t%06X\n", clockCount, c->fi);
	fprintf(f_I, "@%04X\t%06X\n", clockCount, c->I);
	fprintf(f_pcm, "@%04X\t%06X\n", clockCount, c->pcm);
	fprintf(f_pk0, "@%04X\t%06X\n", clockCount, c->pk0);
	fprintf(f_pk1, "@%04X\t%06X\n", clockCount, c->pk1);
	fprintf(f_pk2, "@%04X\t%06X\n", clockCount, c->pk2);
	fprintf(f_sd, "@%04X\t%06X\n", clockCount, c->sd);
	fprintf(f_se, "@%04X\t%06X\n", clockCount, c->se);
	fprintf(f_sez, "@%04X\t%06X\n", clockCount, c->sez);
	fprintf(f_sg, "@%04X\t%06X\n", clockCount, c->sg);
	fprintf(f_sigpk, "@%04X\t%06X\n", clockCount, c->sigpk);
	fprintf(f_slx, "@%04X\t%06X\n", clockCount, c->slx);
	fprintf(f_sp, "@%04X\t%06X\n", clockCount, c->sp);
	fprintf(f_sr, "@%04X\t%06X\n", clockCount, c->sr);
	fprintf(f_sr0, "@%04X\t%06X\n", clockCount, c->sr0);
	fprintf(f_sr1, "@%04X\t%06X\n", clockCount, c->sr1);
	fprintf(f_sr2, "@%04X\t%06X\n", clockCount, c->sr2);
	fprintf(f_td, "@%04X\t%06X\n", clockCount, c->td);
	fprintf(f_tdp, "@%04X\t%06X\n", clockCount, c->tdp);
	fprintf(f_tdr, "@%04X\t%06X\n", clockCount, c->tdr);
	fprintf(f_tr, "@%04X\t%06X\n", clockCount, c->tr);
	fprintf(f_u1, "@%04X\t%06X\n", clockCount, c->u1);
	fprintf(f_u2, "@%04X\t%06X\n", clockCount, c->u2);
	fprintf(f_u3, "@%04X\t%06X\n", clockCount, c->u3);
	fprintf(f_u4, "@%04X\t%06X\n", clockCount, c->u4);
	fprintf(f_u5, "@%04X\t%06X\n", clockCount, c->u5);
	fprintf(f_u6, "@%04X\t%06X\n", clockCount, c->u6);
	fprintf(f_wa1, "@%04X\t%06X\n", clockCount, c->wa1);
	fprintf(f_wa2, "@%04X\t%06X\n", clockCount, c->wa2);
	fprintf(f_wb1, "@%04X\t%06X\n", clockCount, c->wb1);
	fprintf(f_wb2, "@%04X\t%06X\n", clockCount, c->wb2);
	fprintf(f_wb3, "@%04X\t%06X\n", clockCount, c->wb3);
	fprintf(f_wb4, "@%04X\t%06X\n", clockCount, c->wb4);
	fprintf(f_wb5, "@%04X\t%06X\n", clockCount, c->wb5);
	fprintf(f_wb6, "@%04X\t%06X\n", clockCount, c->wb6);
	fprintf(f_wi, "@%04X\t%06X\n", clockCount, c->wi);
	fprintf(f_y, "@%04X\t%06X\n", clockCount, c->y);
	fprintf(f_yl, "@%04X\t%06X\n", clockCount, c->yl);
	fprintf(f_ylp, "@%04X\t%06X\n", clockCount, c->ylp);
	fprintf(f_yu, "@%04X\t%06X\n", clockCount, c->yu);
	fprintf(f_yup, "@%04X\t%06X\n", clockCount, c->yup);
	fprintf(f_yut, "@%04X\t%06X\n", clockCount, c->yut);
	clockCount++;
}

void printChannel(struct channel* c)
{
	printf("a1 = %ld\n", c->a1);
	printf("a1p = %ld\n", c->a1p);
	printf("a1r = %ld\n", c->a1r);
	printf("a1t = %ld\n", c->a1t);
	printf("a2 = %ld\n", c->a2);
	printf("a2p = %ld\n", c->a2p);
	printf("a2r = %ld\n", c->a2r);
	printf("a2t = %ld\n", c->a2t);
	printf("aLaw = %ld\n", c->aLaw);
	printf("al = %ld\n", c->al);
	printf("ap = %ld\n", c->ap);
	printf("app = %ld\n", c->app);
	printf("apr = %ld\n", c->apr);
	printf("ax = %ld\n", c->ax);
	printf("b1 = %ld\n", c->b1);
	printf("b1p = %ld\n", c->b1p);
	printf("b1r = %ld\n", c->b1r);
	printf("b2 = %ld\n", c->b2);
	printf("b2p = %ld\n", c->b2p);
	printf("b2r = %ld\n", c->b2r);
	printf("b3 = %ld\n", c->b3);
	printf("b3p = %ld\n", c->b3p);
	printf("b3r = %ld\n", c->b3r);
	printf("b4 = %ld\n", c->b4);
	printf("b4p = %ld\n", c->b4p);
	printf("b4r = %ld\n", c->b4r);
	printf("b5 = %ld\n", c->b5);
	printf("b5p = %ld\n", c->b5p);
	printf("b5r = %ld\n", c->b5r);
	printf("b6 = %ld\n", c->b6);
	printf("b6p = %ld\n", c->b6p);
	printf("b6r = %ld\n", c->b6r);
	printf("dlnx = %ld\n", c->dlnx);
	printf("dlx = %ld\n", c->dlx);
	printf("dml = %ld\n", c->dml);
	printf("dmlp = %ld\n", c->dmlp);
	printf("dms = %ld\n", c->dms);
	printf("dmsp = %ld\n", c->dmsp);
	printf("dq = %ld\n", c->dq);
	printf("dq0 = %ld\n", c->dq0);
	printf("dq1 = %ld\n", c->dq1);
	printf("dq2 = %ld\n", c->dq2);
	printf("dq3 = %ld\n", c->dq3);
	printf("dq4 = %ld\n", c->dq4);
	printf("dq5 = %ld\n", c->dq5);
	printf("dq6 = %ld\n", c->dq6);
	printf("dql = %ld\n", c->dql);
	printf("dqln = %ld\n", c->dqln);
	printf("dqs = %ld\n", c->dqs);
	printf("dsx = %ld\n", c->dsx);
	printf("dx = %ld\n", c->dx);
	printf("fi = %ld\n", c->fi);
	printf("I = %ld\n", c->I);
	printf("pcm = %ld\n", c->pcm);
	printf("pk0 = %ld\n", c->pk0);
	printf("pk1 = %ld\n", c->pk1);
	printf("pk2 = %ld\n", c->pk2);
	printf("sd = %ld\n", c->sd);
	printf("se = %ld\n", c->se);
	printf("sez = %ld\n", c->sez);
	printf("sg = %ld\n", c->sg);
	printf("sigpk = %ld\n", c->sigpk);
	printf("slx = %ld\n", c->slx);
	printf("sp = %ld\n", c->sp);
	printf("sr = %ld\n", c->sr);
	printf("sr0 = %ld\n", c->sr0);
	printf("sr1 = %ld\n", c->sr1);
	printf("sr2 = %ld\n", c->sr2);
	printf("td = %ld\n", c->td);
	printf("tdp = %ld\n", c->tdp);
	printf("tdr = %ld\n", c->tdr);
	printf("tr = %ld\n", c->tr);
	printf("u1 = %ld\n", c->u1);
	printf("u2 = %ld\n", c->u2);
	printf("u3 = %ld\n", c->u3);
	printf("u4 = %ld\n", c->u4);
	printf("u5 = %ld\n", c->u5);
	printf("u6 = %ld\n", c->u6);
	printf("wa1 = %ld\n", c->wa1);
	printf("wa2 = %ld\n", c->wa2);
	printf("wb1 = %ld\n", c->wb1);
	printf("wb2 = %ld\n", c->wb2);
	printf("wb3 = %ld\n", c->wb3);
	printf("wb4 = %ld\n", c->wb4);
	printf("wb5 = %ld\n", c->wb5);
	printf("wb6 = %ld\n", c->wb6);
	printf("wi = %ld\n", c->wi);
	printf("y = %ld\n", c->y);
	printf("yl = %ld\n", c->yl);
	printf("ylp = %ld\n", c->ylp);
	printf("yu = %ld\n", c->yu);
	printf("yup = %ld\n", c->yup);
	printf("yut = %ld\n", c->yut);
}

int inputCounter = 0;
void printinput(long input)
{
	fprintf(f_input, "@%04X\t%06X\n", inputCounter, input);
	inputCounter++;
}

int outputCounter = 0;
void printoutput(long output)
{
	fprintf(f_output, "@%04X\t%06X\n", outputCounter, output);
	outputCounter++;
}

void closeFiles()
{
if (!ONLY_TOP_LEVEL) {
	fclose(f_a1);
	fclose(f_a1p);
	fclose(f_a1r);
	fclose(f_a1t);
	fclose(f_a2);
	fclose(f_a2p);
	fclose(f_a2r);
	fclose(f_a2t);
	fclose(f_aLaw);
	fclose(f_al);
	fclose(f_ap);
	fclose(f_app);
	fclose(f_apr);
	fclose(f_ax);
	fclose(f_b1);
	fclose(f_b1p);
	fclose(f_b1r);
	fclose(f_b2);
	fclose(f_b2p);
	fclose(f_b2r);
	fclose(f_b3);
	fclose(f_b3p);
	fclose(f_b3r);
	fclose(f_b4);
	fclose(f_b4p);
	fclose(f_b4r);
	fclose(f_b5);
	fclose(f_b5p);
	fclose(f_b5r);
	fclose(f_b6);
	fclose(f_b6p);
	fclose(f_b6r);
	fclose(f_dlnx);
	fclose(f_dlx);
	fclose(f_dml);
	fclose(f_dmlp);
	fclose(f_dms);
	fclose(f_dmsp);
	fclose(f_dq);
	fclose(f_dq0);
	fclose(f_dq1);
	fclose(f_dq2);
	fclose(f_dq3);
	fclose(f_dq4);
	fclose(f_dq5);
	fclose(f_dq6);
	fclose(f_dql);
	fclose(f_dqln);
	fclose(f_dqs);
	fclose(f_dsx);
	fclose(f_dx);
	fclose(f_fi);
	fclose(f_I);
	fclose(f_pcm);
	fclose(f_pk0);
	fclose(f_pk1);
	fclose(f_pk2);
	fclose(f_sd);
	fclose(f_se);
	fclose(f_sez);
	fclose(f_sg);
	fclose(f_sigpk);
	fclose(f_slx);
	fclose(f_sp);
	fclose(f_sr);
	fclose(f_sr0);
	fclose(f_sr1);
	fclose(f_sr2);
	fclose(f_td);
	fclose(f_tdp);
	fclose(f_tdr);
	fclose(f_tr);
	fclose(f_u1);
	fclose(f_u2);
	fclose(f_u3);
	fclose(f_u4);
	fclose(f_u5);
	fclose(f_u6);
	fclose(f_wa1);
	fclose(f_wa2);
	fclose(f_wb1);
	fclose(f_wb2);
	fclose(f_wb3);
	fclose(f_wb4);
	fclose(f_wb5);
	fclose(f_wb6);
	fclose(f_wi);
	fclose(f_y);
	fclose(f_yl);
	fclose(f_ylp);
	fclose(f_yu);
	fclose(f_yup);
	fclose(f_yut);
}
	fclose(f_input);
	fclose(f_output);

	const char* userName = getenv("USER");
	char outPath[64];
	snprintf(outPath, sizeof(outPath), "/tmp/%s_sr_vec_out/vectorSize.t", userName);

	FILE* f_size;
	f_size = fopen(outPath, "w");
	if (ONLY_TOP_LEVEL) {
		fprintf(f_size, "@0000\t%06X\n", inputCounter);
	} else {
		fprintf(f_size, "@0000\t%06X\n", clockCount);
	}
	fclose(f_size);
}

