# ----------------------------------------------------------------
# Assembly source files
#

ADPCM_LIB = libadpcm.a
LIB = ../lib
LIBFLAGS = -L$(LIB) -ladpcm


SRC = enc.c
TGT = enc.elf
LDS = sections.lds

USE_MINI_LIBC = 1
CREATE_FLT_OUTPUT = 1

include ../include/common.mk

